# -*- coding: utf-8 -*-
"""web_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iTCNLyXfYKe_7iA8Ph2lVmQ3CqM__ngY
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import load_model
from PIL import Image
import os

# --- ฟังก์ชันสำหรับโหลด Model แบบ Cache ---
@st.cache_resource
def load_cifar_model():
    # ตรวจสอบว่ามีไฟล์ .keras หรือยัง ถ้ามีให้ใช้ .keras จะปลอดภัยกว่า
    if os.path.exists("cifar10_model.keras"):
        return load_model("cifar10_model.keras")
    else:
        return load_model("cifar10_model.h5")

@st.cache_resource
def load_titanic_model():
    return joblib.load('titanic_model.pkl')

# โหลดข้อมูล CIFAR-10 ครั้งเดียว
@st.cache_data
def load_cifar_data():
    (_, _), (X_test, _) = cifar10.load_data()
    X_test = X_test.astype("float32") / 255.0
    return X_test

X_cifar = load_cifar_data()

# --- ตั้งค่าหน้าเว็บ ---
st.set_page_config(page_title="Project IS 2568", layout="wide")
# --- ฟังก์ชันสำหรับโหลด Model ---
# @st.cache_resource
# def load_ml_model():
#     return joblib.load('titanic_model.pkl')

# @st.cache_resource
# def load_nn_model():
#     return load_model('cifar10_model.h5')

# --- ส่วนของเมนู Sidebar ---
st.sidebar.title("เมนูหลัก")
page = st.sidebar.selectbox("เลือกหน้าเว็บ", [
    "1. ML Explanation (Titanic)",
    "2. ML Testing (Titanic)",
    "3. NN Explanation (CIFAR-10)",
    "4. NN Testing (CIFAR-10)"
])

# ---------------------------------------------------------
# หน้าที่ 1: ML Explanation [cite: 15, 16, 17]
# ---------------------------------------------------------
if page == "1. ML Explanation (Titanic)":
    st.title("🚢 Titanic Survival Prediction Analysis")
    st.divider()

    col1, col2 = st.columns([1, 1])

    with col1:
        st.subheader("1. การเตรียมข้อมูล (Data Pipeline)")
        st.write("""
        ก่อนจะนำข้อมูลเข้าสู่โมเดล เราต้องผ่านกระบวนการ **Data Cleaning** ดังนี้:
        * **Handling Missing Values:** * `Age`: เติมค่าว่างด้วยค่าเฉลี่ย (Mean) 
            * `Embarked`: เติมด้วยฐานนิยม (Mode)
        * **Feature Selection:** เลือกใช้ตัวแปรที่มีอิทธิพลสูง ได้แก่ *Pclass, Sex, Age, Fare*
        * **Categorical Encoding:** แปลงเพศ (Sex) ให้เป็นตัวเลข ($0$ และ $1$) เพื่อให้โมเดลคำนวณได้
        """)

    with col2:
        st.subheader("2. อัลกอริทึม: Ensemble Learning")
        st.info("เราใช้เทคนิค **Voting Classifier** ซึ่งเป็นการรวมพลังของ 3 โมเดลหลัก")
        st.write("""
        1.  **Logistic Regression:** ใช้หาความสัมพันธ์เชิงเส้นเพื่อทำนายโอกาสการรอดชีวิต
        2.  **Random Forest:** ใช้การสร้าง 'ต้นไม้ตัดสินใจ' หลายต้นมาช่วยกันโหวต ลดปัญหา Overfitting
        3.  **SVM (Support Vector Machine):** สร้างเส้นแบ่ง (Hyperplane) ที่ดีที่สุดเพื่อแยกกลุ่มข้อมูล
        """)

    st.divider()
    st.subheader("ทำไมต้อง Ensemble?")
    st.markdown("""
    การใช้ **Majority Voting** ช่วยลดความผิดพลาด (Variance) ที่อาจเกิดขึ้นจากโมเดลใดโมเดลหนึ่งเพียงลำพัง 
    ทำให้การพยากรณ์มีความแม่นยำและเสถียร (Robustness) มากขึ้นเมื่อเจอข้อมูลใหม่ๆ
    """)

# ---------------------------------------------------------
# หน้าที่ 2: ML Testing [cite: 18, 24]
# ---------------------------------------------------------
elif page == "2. ML Testing (Titanic)":
    st.header("ทดสอบโมเดลทำนายการรอดชีวิต")

    # โหลดโมเดลที่สร้างไว้
    try:
        model = joblib.load('titanic_model.pkl')

        col1, col2 = st.columns(2)
        with col1:
            pclass = st.selectbox("ชั้นที่นั่ง (Pclass)", [1, 2, 3])
            sex = st.radio("เพศ", ["ชาย", "หญิง"])
        with col2:
            age = st.slider("อายุ", 0, 100, 30)
            fare = st.number_input("ค่าโดยสาร", value=15.0)

        # แปลงข้อมูลให้เป็นตัวเลขตามที่โมเดลต้องการ
        sex_val = 1 if sex == "ชาย" else 0
        input_data = pd.DataFrame([[pclass, sex_val, age, fare]],
                                  columns=['pclass', 'sex', 'age', 'fare'])

        if st.button("ทำนายผล"):
            prediction = model.predict(input_data)
            if prediction[0] == 1:
                st.success("ยินดีด้วย! ผลการทำนายคือ: รอดชีวิต")
            else:
                st.error("เสียใจด้วย! ผลการทำนายคือ: ไม่รอดชีวิต")
    except:
        st.warning("กรุณาตรวจสอบว่ามีไฟล์ 'titanic_model.pkl' อยู่ในโฟลเดอร์เดียวกับโค้ดนี้")

# ---------------------------------------------------------
# หน้าที่ 3: NN Explanation [cite: 15, 16, 17]
# ---------------------------------------------------------
elif page == "3. NN Explanation (CIFAR-10)":
    st.title("🖼️ CIFAR-10 Image Classification with CNN")
    st.divider()

    # ส่วนบน: การเตรียมข้อมูล
    st.subheader("1. Image Pre-processing")
    st.write("""
    รูปภาพดิจิทัลประกอบด้วยค่า Pixel $0-255$ เราทำการ **Normalization** โดยการหารด้วย $255.0$ เพื่อปรับช่วงข้อมูลให้อยู่ระหว่าง $0$ ถึง $1$
    วิธีนี้ช่วยให้ Gradient ในการฝึกโมเดลไม่ใหญ่จนเกินไปและทำให้ AI เรียนรู้ได้เร็วขึ้น
    """)

    st.divider()

    # ส่วนล่าง: โครงสร้าง Neural Network
    st.subheader("2. โครงสร้าง Convolutional Neural Network (CNN)")
    
    c1, c2, c3 = st.columns(3)
    
    with c1:
        st.markdown("### **Feature Extraction**")
        st.write("""
        * **Convolutional Layer:** ใช้ Filters เลื่อนไปทั่วภาพเพื่อดึงลักษณะเด่น (ขอบภาพ, รูปทรง)
        * **ReLU Activation:** ฟังก์ชัน $f(x) = \max(0, x)$ เพื่อตัดค่าติดลบออกไป
        """)
        
    with c2:
        st.markdown("### **Dimension Reduction**")
        st.write("""
        * **Max Pooling:** การสุ่มเลือกค่าที่มากที่สุดในพื้นที่ เพื่อลดขนาดข้อมูลแต่ยังรักษาลักษณะสำคัญไว้
        """)

    with c3:
        st.markdown("### **Classification**")
        st.write("""
        * **Flatten:** แปลงข้อมูลภาพจากมิติสูงให้เป็นเส้นตรง
        * **Dense Layer:** ชั้นประมวลผลสุดท้ายเพื่อจัดหมวดหมู่ภาพเป็น 10 ประเภท (Softmax)
        """)

    st.success("โมเดล CNN นี้มีความสามารถพิเศษในการมองเห็น 'ความสัมพันธ์เชิงพื้นที่' ของเม็ดสี ซึ่งดีกว่า Neural Network แบบธรรมดามาก")

# ---------------------------------------------------------
# หน้าที่ 4: NN Testing [cite: 18, 24]
# ---------------------------------------------------------
elif page == "4. NN Testing (CIFAR-10)":
    st.header("ทดสอบโมเดลจำแนกรูปภาพ (CIFAR-10)")
    
    try:
        # เรียกใช้ฟังก์ชันโหลดโมเดลที่ทำ Cache ไว้
        nn_model = load_cifar_model() 
        
        class_names = ["airplane", "automobile", "bird", "cat", "deer", "dog", "frog", "horse", "ship", "truck"]
        index = st.slider("เลือกภาพ (0-9999):", 0, 9999, 0)
        
        image = X_cifar[index]
        
        # ใช้ชื่อตัวแปรที่โหลดมา (nn_model)
        pred = nn_model.predict(image.reshape(1, 32, 32, 3))
        label = class_names[np.argmax(pred)]
        
        st.image(image, caption=f"Prediction: {label}", width=150)
    except Exception as e:
        st.error(f"เกิดข้อผิดพลาดในการโหลดโมเดล: {e}")
        st.info("คำแนะนำ: ลองเซฟโมเดลเป็นนามสกุล .keras ในเครื่องคุณก่อนแล้วค่อย Upload ใหม่")
