# -*- coding: utf-8 -*-
"""web_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iTCNLyXfYKe_7iA8Ph2lVmQ3CqM__ngY
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib
from tensorflow.keras.models import load_model
from PIL import Image

# --- ตั้งค่าหน้าเว็บ ---
st.set_page_config(page_title="Project IS 2568", layout="wide")

# --- ฟังก์ชันสำหรับโหลด Model ---
# @st.cache_resource
# def load_ml_model():
#     return joblib.load('titanic_model.pkl')

# @st.cache_resource
# def load_nn_model():
#     return load_model('cifar10_model.h5')

# --- ส่วนของเมนู Sidebar ---
st.sidebar.title("เมนูหลัก")
page = st.sidebar.selectbox("เลือกหน้าเว็บ", [
    "1. ML Explanation (Titanic)",
    "2. ML Testing (Titanic)",
    "3. NN Explanation (CIFAR-10)",
    "4. NN Testing (CIFAR-10)"
])

# ---------------------------------------------------------
# หน้าที่ 1: ML Explanation [cite: 15, 16, 17]
# ---------------------------------------------------------
if page == "1. ML Explanation (Titanic)":
    st.header("การพัฒนาโมเดล Ensemble Machine Learning (Titanic)")
    st.subheader("1. การเตรียมข้อมูล (Data Preparation)")
    st.write("- **Dataset**: ข้อมูลผู้โดยสาร Titanic จาก Kaggle [cite: 3, 4]")
    st.write("- **ความไม่สมบูรณ์**: พบค่าว่างใน Age และ Embarked จึงทำการเติมค่าด้วย Mean และ Mode [cite: 6, 7]")
    st.write("- **Feature Engineering**: แปลง Sex และ Embarked เป็นตัวเลขเพื่อเข้าโมเดล [cite: 5]")

    st.subheader("2. ทฤษฎีอัลกอริทึม")
    st.write("ใช้วิธี **Ensemble Learning (Voting)** ที่ประกอบด้วย 3 โมเดล[cite: 10]:")
    st.write("1. Logistic Regression 2. Random Forest 3. Support Vector Machine (SVM)")

    st.subheader("3. แหล่งอ้างอิง")
    st.write("- Scikit-learn Documentation")

# ---------------------------------------------------------
# หน้าที่ 2: ML Testing [cite: 18, 24]
# ---------------------------------------------------------
elif page == "2. ML Testing (Titanic)":
    st.header("ทดสอบโมเดลทำนายการรอดชีวิต")

    # โหลดโมเดลที่สร้างไว้
    try:
        model = joblib.load('titanic_model.pkl')

        col1, col2 = st.columns(2)
        with col1:
            pclass = st.selectbox("ชั้นที่นั่ง (Pclass)", [1, 2, 3])
            sex = st.radio("เพศ", ["ชาย", "หญิง"])
        with col2:
            age = st.slider("อายุ", 0, 100, 30)
            fare = st.number_input("ค่าโดยสาร", value=15.0)

        # แปลงข้อมูลให้เป็นตัวเลขตามที่โมเดลต้องการ
        sex_val = 1 if sex == "ชาย" else 0
        input_data = pd.DataFrame([[pclass, sex_val, age, fare]],
                                  columns=['pclass', 'sex', 'age', 'fare'])

        if st.button("ทำนายผล"):
            prediction = model.predict(input_data)
            if prediction[0] == 1:
                st.success("ยินดีด้วย! ผลการทำนายคือ: รอดชีวิต")
            else:
                st.error("เสียใจด้วย! ผลการทำนายคือ: ไม่รอดชีวิต")
    except:
        st.warning("กรุณาตรวจสอบว่ามีไฟล์ 'titanic_model.pkl' อยู่ในโฟลเดอร์เดียวกับโค้ดนี้")

# ---------------------------------------------------------
# หน้าที่ 3: NN Explanation [cite: 15, 16, 17]
# ---------------------------------------------------------
elif page == "3. NN Explanation (CIFAR-10)":
    st.header("การพัฒนาโมเดล Neural Network (CIFAR-10)")
    st.subheader("1. การเตรียมข้อมูล")
    st.write("- ทำการ Normalize รูปภาพโดยหารด้วย 255.0 เพื่อให้ค่า Pixel อยู่ในช่วง $0$ ถึง $1$")

    st.subheader("2. ทฤษฎีอัลกอริทึม")
    st.write("ใช้โครงสร้าง **Convolutional Neural Network (CNN)** [cite: 12, 13]")
    st.write("- Convolutional Layer สำหรับดึงลักษณะเด่น")
    st.write("- Max Pooling สำหรับลดขนาดข้อมูล")
    st.write("- Dense Layer สำหรับจัดหมวดหมู่ 10 ประเภท")

# ---------------------------------------------------------
# หน้าที่ 4: NN Testing [cite: 18, 24]
# ---------------------------------------------------------
elif page == "4. NN Testing (CIFAR-10)":
    st.header("ทดสอบโมเดลจำแนกรูปภาพ (CIFAR-10)")
    class_names = ["airplane", "automobile", "bird", "cat", "deer", "dog", "frog", "horse", "ship", "truck"]
    index = st.slider("เลือกภาพ (0-9999):", 0, 9999, 0)
    image = X_cifar[index]
    pred = cifar10_model.predict(image.reshape(1, 32, 32, 3))
    label = class_names[np.argmax(pred)]
    st.image(image, caption=f"Prediction: {label}", width=150)
